import {
  DashboardResponse,
  DecisionMemory,
  DemoState,
  SafetyAlert,
  SafetyStatus,
  SimilarContext,
  Task,
  TrainingModule,
  TrainingProgress,
  TrainingRecommendation,
  TrajectoryScenario,
} from '../types';

export const FALLBACK_SCENARIOS: TrajectoryScenario[] = [
  {
    scenario_id: 'SCEN-01-CONTINUE',
    action_id: 'ACT-CONTINUE',
    title: 'Trajectory A: CONTINUE (Baseline Drift)',
    description: 'Maintain bench stance and wait for delayed haul fleet at current excavator location.',
    constraint_status: 'FEASIBLE',
    selectable: true,
    predicted_outcome: {
      duration_minutes: 162.0,
      shift_delay_minutes: 17.0,
      fuel_liters: 184.0,
      idle_minutes: 18.0,
      productivity_tons_per_hr: 92.0,
      safety_risk_score: 18.0,
      time_saved_minutes: 0.0,
      fuel_saved_liters: 0.0,
    },
    explanation: 'Passive path; accumulates 18 min dead idle, rain arrives at 11:30 AM before trench seal, incurring 17 min handoff delay.',
    why_trace: {
      signal: 'Haul Fleet Delay at Crusher',
      value: '18.2 min gap',
      baseline: '4.5 min scheduled return',
      interpretation: 'Waiting without re-sequencing forces 18 min dead idle at 1800 RPM.',
      source: 'Haul Fleet GPS & Crusher Queue Telemetry',
    },
    consequence_graph: {
      graph_id: 'CG-CONTINUE-01',
      scenario_id: 'SCEN-01-CONTINUE',
      root_action: 'Hold Current Stance & Wait',
      summary: 'Waiting causes 18 min idle; rain hits at 11:30 AM on unsealed trench; deadline missed by 17 min.',
      nodes: [
        { node_id: 'N1', type: 'DECISION', title: 'Hold Position & Wait', value: '18 min wait', unit: 'min', severity: 'WARNING', explanation: 'Operator idles while trucks are queued at crusher.' },
        { node_id: 'N2', type: 'MACHINE_EFFECT', title: 'Engine Low-Idle Standby', value: '1800 RPM', unit: 'RPM', severity: 'WARNING', explanation: 'Engine idles at high RPM burning 18.5 L/hr.' },
        { node_id: 'N3', type: 'FUEL_EFFECT', title: 'Dead Idle Fuel Waste', value: '+14.8 L', unit: 'liters', severity: 'WARNING', explanation: 'Unproductive fuel consumed with zero tons moved.' },
        { node_id: 'N4', type: 'TASK_EFFECT', title: 'Truck Queue Shockwave', value: '4 trucks', unit: 'queued', severity: 'WARNING', explanation: 'Delayed trucks arrive simultaneously causing queuing bottleneck.' },
        { node_id: 'N5', type: 'OUTCOME', title: 'Rain Delay Compounding', value: '+17.0 min', unit: 'min', severity: 'CRITICAL', explanation: 'Trench floor unsealed when rain hits; misses 14:00 shift handoff.' },
      ],
      edges: [
        { source: 'N1', target: 'N2', relationship: 'CAUSES', explanation: 'Truck delay forces excavator into prolonged standby.' },
        { source: 'N2', target: 'N3', relationship: 'INCREASES', explanation: 'High idle consumes fuel unproductively.' },
        { source: 'N2', target: 'N4', relationship: 'TRIGGERS', explanation: 'Platoon bunches on haul road entry narrow.' },
        { source: 'N4', target: 'N5', relationship: 'CAUSES', explanation: 'Compounded queue delays breach 14:00 deadline.' },
      ],
    },
  },
  {
    scenario_id: 'SCEN-02-RESEQUENCE',
    action_id: 'ACT-RESEQUENCE',
    title: 'Trajectory B: RESEQUENCE (Overburden Pre-Stripping)',
    description: 'Switch immediately to pre-stripping 180t overburden on Upper Bench 3; direct load trucks on return.',
    constraint_status: 'FEASIBLE',
    selectable: true,
    predicted_outcome: {
      duration_minutes: 145.0,
      shift_delay_minutes: -17.0,
      fuel_liters: 168.0,
      idle_minutes: 0.0,
      productivity_tons_per_hr: 118.0,
      safety_risk_score: 12.0,
      time_saved_minutes: 17.0,
      fuel_saved_liters: 14.8,
    },
    explanation: 'Clears 180t overburden during truck gap; soil loosened in advance cuts truck load time by 35s per truck; seals trench 12 min early.',
    why_trace: {
      signal: 'Upper Bench 3 Overburden Readiness',
      value: '8.0° slope grade',
      baseline: '15.0° max safety limit',
      interpretation: 'Slope is validated safe; pre-stripping consumes zero dead idle and preps soil.',
      source: 'Safety Slope Sensor & Operations Task Dispatch',
    },
    consequence_graph: {
      graph_id: 'CG-RESEQUENCE-01',
      scenario_id: 'SCEN-02-RESEQUENCE',
      root_action: 'Re-sequence to Bench 3 Cut',
      summary: 'Pre-stripping eliminates idle waste, loosens bench soil in advance, and allows rapid truck clearance before rain.',
      nodes: [
        { node_id: 'N1', type: 'DECISION', title: 'Pivot to Bench 3 Cut', value: '180 tons', unit: 'tons', severity: 'BENEFICIAL', explanation: 'Operator shifts to Upper Bench 3 overburden cut.' },
        { node_id: 'N2', type: 'MACHINE_EFFECT', title: 'Optimal Power Band', value: '100%', unit: 'load', severity: 'BENEFICIAL', explanation: 'Engine operates at peak hydraulic efficiency with zero dead idle.' },
        { node_id: 'N3', type: 'TASK_EFFECT', title: 'Soil Pre-loosened', value: '-35', unit: 'sec/truck', severity: 'BENEFICIAL', explanation: 'Truck loading cycle cuts 35 seconds per bucket load.' },
        { node_id: 'N4', type: 'FUEL_EFFECT', title: 'Fuel Saved', value: '-14.8', unit: 'L', severity: 'BENEFICIAL', explanation: 'Net fuel burn reduced across remaining shift tons.' },
        { node_id: 'N5', type: 'OUTCOME', title: 'Early Shift Completion', value: '-12.0', unit: 'min', severity: 'BENEFICIAL', explanation: 'Trench sealed and completed 12 mins before rain onset.' },
      ],
      edges: [
        { source: 'N1', target: 'N2', relationship: 'CAUSES', explanation: 'Shifting work keeps machine in continuous productive load.' },
        { source: 'N2', target: 'N3', relationship: 'ENABLES', explanation: 'Pre-loosened soil reduces bucket breakout resistance.' },
        { source: 'N3', target: 'N4', relationship: 'REDUCES', explanation: 'Faster truck filling cuts overall engine running time.' },
        { source: 'N4', target: 'N5', relationship: 'CAUSES', explanation: 'Absorbs truck queue and finishes before rain front arrives.' },
      ],
    },
  },
  {
    scenario_id: 'SCEN-03-REPOSITION',
    action_id: 'ACT-REPOSITION',
    title: 'Trajectory C: REPOSITION (Face Angle Optimization)',
    description: 'Walk machine 12m West along Bench 2 to reduce bucket swing arc from 48° to 32° and remark truck spotting cone.',
    constraint_status: 'FEASIBLE',
    selectable: true,
    predicted_outcome: {
      duration_minutes: 149.0,
      shift_delay_minutes: -13.0,
      fuel_liters: 172.0,
      idle_minutes: 4.0,
      productivity_tons_per_hr: 112.0,
      safety_risk_score: 14.0,
      time_saved_minutes: 13.0,
      fuel_saved_liters: 11.2,
    },
    explanation: '4 min walk time; reduces swing arc by 16°; hydraulic slew pressure drops 14%; cycle time drops from 28.5s to 22.0s per pass.',
    why_trace: {
      signal: 'Highwall Edge Proximity',
      value: '6.5m standoff',
      baseline: '4.0m minimum safety margin',
      interpretation: 'Reposition stance maintains safe highwall standoff while improving swing geometry.',
      source: 'LiDAR Terrain & Proximity Sensor',
    },
    consequence_graph: {
      graph_id: 'CG-REPOSITION-01',
      scenario_id: 'SCEN-03-REPOSITION',
      root_action: 'Walk Machine 12m West',
      summary: 'Reduced boom swing arc cuts cycle time by 6.5s per pass, absorbing the haul fleet queue.',
      nodes: [
        { node_id: 'N1', type: 'DECISION', title: 'Walk 12m West', value: '4 min walk', unit: 'min', severity: 'NEUTRAL', explanation: 'Operator re-aligns digging face by 15 degrees.' },
        { node_id: 'N2', type: 'MACHINE_EFFECT', title: 'Swing Arc Reduced', value: '48° ➔ 32°', unit: 'deg', severity: 'BENEFICIAL', explanation: 'Slew motor hydraulic pressure drops 14%.' },
        { node_id: 'N3', type: 'TASK_EFFECT', title: 'Cycle Time Cut', value: '28.5s ➔ 22.0s', unit: 'sec', severity: 'BENEFICIAL', explanation: 'Shaves 6.5s off every bucket pass.' },
        { node_id: 'N4', type: 'FUEL_EFFECT', title: 'Hydraulic Fuel Saved', value: '-11.2', unit: 'L', severity: 'BENEFICIAL', explanation: 'Lower hydraulic strain across remaining 500 tons.' },
        { node_id: 'N5', type: 'OUTCOME', title: '8 Min Early Finish', value: '-8.0', unit: 'min', severity: 'BENEFICIAL', explanation: 'Faster truck turnaround clears queue before rain arrives.' },
      ],
      edges: [
        { source: 'N1', target: 'N2', relationship: 'CAUSES', explanation: 'Repositioning face geometry tightens machine-to-truck swing arc.' },
        { source: 'N2', target: 'N3', relationship: 'SPEEDS_UP', explanation: 'Shorter swing path directly reduces cycle duration.' },
        { source: 'N3', target: 'N4', relationship: 'REDUCES', explanation: 'Faster cycles decrease total hydraulic pumping energy.' },
        { source: 'N4', target: 'N5', relationship: 'CAUSES', explanation: 'Platoon queue absorbed without shift delay.' },
      ],
    },
  },
  {
    scenario_id: 'SCEN-04-STEEP-CUT',
    action_id: 'ACT-STEEP-CUT',
    title: 'Trajectory D: STEEP CUT (Highwall Over-cut)',
    description: 'Attempt aggressive shortcut cut along North highwall crest to shorten haul distance.',
    constraint_status: 'REJECTED',
    selectable: false,
    rejection_reason: 'REJECTED — SAFETY/OPERATIONAL CONSTRAINT',
    constraint_detail: {
      constraint: 'SLOPE_STABILITY_GRADE_LIMIT',
      value: '18.5° slope grade',
      threshold: '15.0° maximum permissible grade',
      explanation: 'Cut geometry produces an 18.5° grade exceeding geotechnical slope stability threshold (15.0° max). Unsafe option rejected by safety constraint validator.',
    },
    predicted_outcome: {
      duration_minutes: 140.0,
      shift_delay_minutes: -22.0,
      fuel_liters: 162.0,
      idle_minutes: 0.0,
      productivity_tons_per_hr: 125.0,
      safety_risk_score: 85.0,
      time_saved_minutes: 22.0,
      fuel_saved_liters: 22.0,
    },
    explanation: 'REJECTED — SAFETY/OPERATIONAL CONSTRAINT: Violates highwall stability limit. Safety constraints reject this trajectory deterministically; safety is never traded off for productivity.',
    why_trace: {
      signal: 'Highwall Slope Stability Model',
      value: '18.5° slope',
      baseline: '15.0° max stability limit',
      interpretation: 'Slope instability breach triggers mandatory deterministic rejection.',
      source: 'Safety Service Physical Constraint Engine',
    },
    consequence_graph: {
      graph_id: 'CG-STEEP-01',
      scenario_id: 'SCEN-04-STEEP-CUT',
      root_action: 'Steep Cut Shortcut',
      summary: 'Candidate trajectory rejected by safety constraints.',
      nodes: [
        { node_id: 'N1', type: 'DECISION', title: 'Steep Cut', value: '18.5° cut', unit: 'deg', severity: 'CRITICAL', explanation: 'Attempted steep cut.' },
        { node_id: 'N2', type: 'SAFETY_EFFECT', title: 'Slope Failure Risk', value: 'BREACH', unit: 'status', severity: 'CRITICAL', explanation: 'Highwall slump risk exceeds threshold.' },
        { node_id: 'N3', type: 'OUTCOME', title: 'Rejected', value: 'REJECTED', unit: 'gate', severity: 'CRITICAL', explanation: 'Deterministic safety gate blocks recommendation.' },
      ],
      edges: [
        { source: 'N1', target: 'N2', relationship: 'TRIGGERS', explanation: 'Exceeds 15° geotechnical limit.' },
        { source: 'N2', target: 'N3', relationship: 'REJECTS', explanation: 'Safety validator rejects candidate path.' },
      ],
    },
  },
];

const STEP_DEFINITIONS: Record<number, any> = {
  1: {
    name: 'STATE 1: NORMAL',
    title: 'Normal Shift Baseline',
    attention_mode: 'NORMAL',
    attention_reason: 'Nominal operating parameters.',
    summary: 'Shift running smoothly on Bench 2. Seatbelt fastened, 0 proximity hazards, normal 9.8% idle, target pace 104.5%.',
    seatbelt: true,
    proximity_hazards: 0,
    idle_pct: 9.8,
    fuel_burn_rate_lph: 14.2,
    safety_score: 98.0,
    behaviour_score: 94.0,
    decision_point_active: false,
    top_action: {
      action_id: 'NBA-01',
      title: 'Maintain Production Pace',
      rationale: 'Digging speed is 4.5% above baseline. Trench grade on schedule.',
      estimated_benefit: 'On schedule for 14:00 shift handoff',
      priority: 'NORMAL',
    },
    training_rec: null,
  },
  2: {
    name: 'STATE 2: SEATBELT EVENT',
    title: 'Seatbelt Compliance Event',
    attention_mode: 'SAFETY_FOCUS',
    attention_reason: 'Seatbelt unfastened during machine operation.',
    summary: 'Operator unbuckled harness while adjusting seat during cycle pause. Visual alert illuminated.',
    seatbelt: false,
    proximity_hazards: 0,
    idle_pct: 10.0,
    fuel_burn_rate_lph: 14.2,
    safety_score: 72.0,
    behaviour_score: 88.0,
    decision_point_active: false,
    top_action: {
      action_id: 'NBA-SAFE-01',
      title: 'Fasten 3-Point Safety Harness',
      rationale: 'Cab interlock detected unbuckled seatbelt during engine engagement.',
      estimated_benefit: 'Restores full compliance streak',
      priority: 'CRITICAL',
    },
    training_rec: {
      module_id: 'SAFE_START_01',
      module_title: 'Safe Start Check',
      reason: 'Seatbelt non-compliance detected. Review safe operating procedures and startup sequence before continuing.',
      urgency: 'HIGH',
    },
  },
  3: {
    name: 'STATE 3: PROXIMITY EVENT',
    title: 'Proximity Hazard Trigger',
    attention_mode: 'SAFETY_FOCUS',
    attention_reason: 'Support vehicle within dynamic swing radius (14m < 15m threshold).',
    summary: 'Support utility vehicle approaches within 14m perimeter on blind counterweight side.',
    seatbelt: true,
    proximity_hazards: 1,
    idle_pct: 10.2,
    fuel_burn_rate_lph: 14.2,
    safety_score: 68.0,
    behaviour_score: 90.0,
    decision_point_active: false,
    top_action: {
      action_id: 'NBA-PROX-01',
      title: 'Halt Swing and Ground Bucket',
      rationale: 'Support utility vehicle inside 15m exclusion boundary.',
      estimated_benefit: 'Neutralizes collision hazard',
      priority: 'CRITICAL',
    },
    training_rec: {
      module_id: 'PROXIMITY_RESPONSE_01',
      module_title: 'Proximity Response',
      reason: 'Proximity boundary alert triggered. Review site hazard identification and response guidelines.',
      urgency: 'HIGH',
    },
  },
  4: {
    name: 'STATE 4: QUEUE IMBALANCE / HIGH IDLE',
    title: 'Haul Fleet Cycle Bunching & High Idle Spike',
    attention_mode: 'EFFICIENCY_FOCUS',
    attention_reason: 'Low-idle fuel burn spiking due to haul fleet cycle mismatch.',
    summary: 'Crusher bottleneck creates 18-minute haul truck arrival gap. Excavator idling at 1800 RPM (14.8% idle spike).',
    seatbelt: true,
    proximity_hazards: 0,
    idle_pct: 14.8,
    fuel_burn_rate_lph: 18.5,
    safety_score: 96.0,
    behaviour_score: 76.0,
    decision_point_active: false,
    top_action: {
      action_id: 'NBA-IDLE-01',
      title: 'Engage Auto-Idle Control or Pre-strip Overburden',
      rationale: 'Truck gap at crusher is causing unproductive 18.5 L/hr fuel burn.',
      estimated_benefit: 'Saves 18.5 L/hr fuel waste',
      priority: 'HIGH',
    },
    training_rec: {
      module_id: 'IDLE_EFFICIENCY_01',
      module_title: 'Idle Efficiency Response',
      reason: 'Excessive low-idle operation observed. Review engine power management and queue mitigation techniques.',
      urgency: 'MEDIUM',
    },
  },
  5: {
    name: 'STATE 5: DECISION POINT',
    title: 'Decision Point Detected: The 17-Minute Trap',
    attention_mode: 'DECISION_FOCUS',
    attention_reason: 'Haul fleet queue mismatch and rain front create compounding 17-minute delay trap.',
    summary: '18-minute truck gap compounding with incoming rain front at 11:30 AM. Passive continuation guarantees a 17-minute shift overrun.',
    seatbelt: true,
    proximity_hazards: 0,
    idle_pct: 14.8,
    fuel_burn_rate_lph: 18.5,
    safety_score: 98.0,
    behaviour_score: 78.0,
    decision_point_active: true,
    top_action: {
      action_id: 'ACT-EVAL-TRAJECTORY',
      title: 'Compare Available Recovery Trajectories',
      rationale: 'Current queue imbalance and incoming rain are projected to delay shift completion.',
      estimated_benefit: 'Recover 17 minutes and avoid trench water accumulation',
      priority: 'HIGH',
    },
    training_rec: {
      module_id: 'DECISION_AWARENESS_01',
      module_title: 'Decision Awareness',
      reason: 'Emergent tactical decision point encountered. Review consequence graphs and trajectory trade-offs.',
      urgency: 'MEDIUM',
    },
  },
  6: {
    name: 'STATE 6: TRAJECTORY COMPARISON',
    title: 'Trajectory Alternatives & Consequence Graph',
    attention_mode: 'DECISION_FOCUS',
    attention_reason: 'Compare candidate trajectories: Continue, Resequence, or Reposition.',
    summary: 'Three candidate trajectories evaluated against safety constraints. Consequence graph visualizes causal chain.',
    seatbelt: true,
    proximity_hazards: 0,
    idle_pct: 14.8,
    fuel_burn_rate_lph: 18.5,
    safety_score: 98.0,
    behaviour_score: 78.0,
    decision_point_active: true,
    top_action: {
      action_id: 'ACT-CHOOSE-TRAJECTORY',
      title: 'Select Tactical Trajectory',
      rationale: 'Trajectory B (Resequence) saves 17 min and 14.8L fuel with validated 8° slope safety.',
      estimated_benefit: 'Finish 12 min early before rain onset',
      priority: 'HIGH',
    },
    training_rec: {
      module_id: 'DECISION_AWARENESS_01',
      module_title: 'Decision Awareness',
      reason: 'Review alternative trajectories and understand consequence flows.',
      urgency: 'MEDIUM',
    },
  },
  7: {
    name: 'STATE 7: OPERATOR CHOICE',
    title: 'Operator Decision Committed',
    attention_mode: 'PLANNING_FOCUS',
    attention_reason: 'Operator committed Trajectory B (Resequence to Upper Bench 3). Active task updated.',
    summary: "Operator chose Trajectory B (RESEQUENCE). Rationale recorded: 'Bypassed haul truck queue before rain onset'.",
    seatbelt: true,
    proximity_hazards: 0,
    idle_pct: 8.5,
    fuel_burn_rate_lph: 16.0,
    safety_score: 98.0,
    behaviour_score: 92.0,
    decision_point_active: false,
    top_action: {
      action_id: 'ACT-EXECUTE-BENCH3',
      title: 'Execute Bench 3 Overburden Cut',
      rationale: 'Pre-stripping 180 tons of soft soil into temporary stockpile.',
      estimated_benefit: 'Soil pre-loosened before truck arrival',
      priority: 'NORMAL',
    },
    training_rec: null,
  },
  8: {
    name: 'STATE 8: OUTCOME REPLAY',
    title: 'Outcome Replay & Prediction Audit',
    attention_mode: 'NORMAL',
    attention_reason: 'Trajectory executed. Predicted outcome audited against simulated actual outcome.',
    summary: 'Simulation advances: 180 tons moved, trucks loaded at rapid pace. Predicted vs. simulated outcome shows high model accuracy.',
    seatbelt: true,
    proximity_hazards: 0,
    idle_pct: 5.2,
    fuel_burn_rate_lph: 15.1,
    safety_score: 99.0,
    behaviour_score: 95.0,
    decision_point_active: false,
    top_action: {
      action_id: 'ACT-COMPLETE-STAGE',
      title: 'Trench Ready for Final Handoff',
      rationale: 'Overburden cleared, trucks dispatched, trench sealed before rain front.',
      estimated_benefit: '15.8 min actual time saved',
      priority: 'NORMAL',
    },
    training_rec: null,
  },
  9: {
    name: 'STATE 9: DECISION MEMORY',
    title: 'Decision Memory Stored',
    attention_mode: 'NORMAL',
    attention_reason: 'Decision context and validated outcome saved to organizational memory.',
    summary: 'Decision DEC-OP1001-001 with context signature SIG-BENCH2-WET-TRENCH saved in PostgreSQL decision store.',
    seatbelt: true,
    proximity_hazards: 0,
    idle_pct: 5.2,
    fuel_burn_rate_lph: 14.8,
    safety_score: 99.0,
    behaviour_score: 96.0,
    decision_point_active: false,
    top_action: {
      action_id: 'ACT-REVIEW-MEMORY',
      title: 'Decision Stored in Shift Twin Memory',
      rationale: 'Historical evidence available for future similar context match.',
      estimated_benefit: 'Organizational knowledge preserved',
      priority: 'NORMAL',
    },
    training_rec: null,
  },
  10: {
    name: 'STATE 10: SIMILAR CONTEXT',
    title: 'Similar Context Reuse in Future Shift',
    attention_mode: 'DECISION_FOCUS',
    attention_reason: 'Historical similar decision context detected: SIG-BENCH2-WET-TRENCH (94% match).',
    summary: 'In an upcoming shift, an operator encounters an excavator-truck mismatch under wet conditions. Past decision surfaced: Operator OP1001 saved 15.8 mins.',
    seatbelt: true,
    proximity_hazards: 0,
    idle_pct: 13.5,
    fuel_burn_rate_lph: 17.8,
    safety_score: 98.0,
    behaviour_score: 82.0,
    decision_point_active: true,
    top_action: {
      action_id: 'ACT-REUSE-RESEQUENCE',
      title: 'Apply Proven Trajectory B (Resequence)',
      rationale: 'Similar historical shift DEC-OP1001-001 achieved 15.8 mins savings under identical wet conditions.',
      estimated_benefit: 'Proven 15.8 min savings & 15.6L fuel reduction',
      priority: 'HIGH',
    },
    training_rec: {
      module_id: 'DECISION_AWARENESS_01',
      module_title: 'Decision Awareness',
      reason: 'Similar decision pattern detected. Review the consequence mechanics before committing.',
      urgency: 'MEDIUM',
    },
  },
};

export function getFallbackDemoState(step: number, chosenScenario?: string): DemoState {
  const s = Math.max(1, Math.min(10, step));
  const info = STEP_DEFINITIONS[s] || STEP_DEFINITIONS[1];
  const chosen = chosenScenario || (s >= 7 ? 'SCEN-02-RESEQUENCE' : null);

  const decisionPoint =
    info.decision_point_active || s >= 5
      ? {
          decision_point_id: 'DP-BENCH2-HAUL-01',
          timestamp: '2026-09-23T10:45:00Z',
          operator_id: 'OP1001',
          machine_id: 'EXC-CAT-349D',
          task_id: 'T002',
          trigger_type: 'QUEUE_IMBALANCE',
          severity: 'HIGH' as const,
          summary: 'Haul fleet cycle mismatch and incoming rain front create a projected 17-minute shift delay trap.',
          evidence: {
            truck_gap_projected_minutes: 18.2,
            truck_queue_on_arrival: 4,
            current_idle_pct: info.idle_pct,
            ground_saturation_trend_pct_per_hr: 12.0,
            baseline_eta_delay_minutes: 17.4,
            weather_alert: 'Rain arriving at 11:30 AM (North Bench traction loss)',
          },
          available_actions: ['ACT-CONTINUE', 'ACT-RESEQUENCE', 'ACT-REPOSITION'],
        }
      : null;

  const outcomeReplay =
    s >= 7
      ? {
          decision_id: 'DEC-OP1001-001',
          chosen_scenario: chosen || 'SCEN-02-RESEQUENCE',
          predicted_outcome: {
            eta_minutes: 145.0,
            fuel_liters: 168.0,
            idle_minutes: 0.0,
            shift_delay_minutes: -17.0,
          },
          actual_outcome: {
            eta_minutes: 146.5,
            fuel_liters: 167.2,
            idle_minutes: 1.2,
            shift_delay_minutes: -15.8,
          },
          prediction_error: {
            eta_delta_minutes: 1.5,
            fuel_delta_liters: -0.8,
            idle_delta_minutes: 1.2,
            accuracy_pct: 98.9,
          },
          drift_status: 'WITHIN_TOLERANCE',
          is_simulated: true,
          simulation_label: 'SIMULATED OUTCOME — PROJECTION AUDITED',
        }
      : null;

  return {
    demo_mode: true,
    current_step: s,
    total_steps: 10,
    step_name: info.name,
    title: info.title,
    summary: info.summary,
    attention_mode: info.attention_mode,
    attention_reason: info.attention_reason,
    timestamp: new Date().toISOString(),
    operator_id: 'OP1001',
    machine_id: 'EXC-CAT-349D',
    task_id: 'T002',
    seatbelt_fastened: info.seatbelt,
    active_hazard_count: info.proximity_hazards,
    idle_percentage: info.idle_pct,
    fuel_burn_rate_lph: info.fuel_burn_rate_lph,
    safety_score: info.safety_score,
    behaviour_score: info.behaviour_score,
    next_best_action: info.top_action,
    top_training_recommendation: info.training_rec,
    decision_point: decisionPoint,
    scenarios: FALLBACK_SCENARIOS,
    chosen_scenario: chosen,
    operator_reason: s >= 7 ? 'Bypassed haul truck queue before rain onset.' : null,
    reason_category: s >= 7 ? 'schedule' : null,
    outcome_replay: outcomeReplay,
    similar_context: s === 10 ? getFallbackSimilarContext() : null,
  };
}

export function getFallbackDashboard(step: number, chosenScenario?: string): DashboardResponse {
  const demo = getFallbackDemoState(step, chosenScenario);
  return {
    operator_id: 'OP1001',
    timestamp: new Date().toISOString(),
    shift_twin_summary: {
      twin_id: 'TWIN-OP1001-LIVE',
      operator_id: 'OP1001',
      machine_id: 'EXC-CAT-349D',
      current_task_id: 'T002',
      updated_at: new Date().toISOString(),
      shift_health_score: Math.round((demo.safety_score + demo.behaviour_score) / 2),
      attention_mode: demo.attention_mode,
      attention_reason: demo.attention_reason,
      environment: {
        weather_condition: step >= 5 ? 'OVERCAST_RAIN_APPROACHING' : 'CLEAR',
        ambient_temp_c: 23.5,
        ground_saturation_pct: step >= 5 ? 28.0 : 12.0,
        visibility_level: 'OPTIMAL',
      },
      safety: {
        seatbelt_status: demo.seatbelt_fastened,
        seatbelt_compliance_pct: demo.seatbelt_fastened ? 99.4 : 74.2,
        active_proximity_hazards: demo.active_hazard_count,
        safety_score: demo.safety_score,
      },
      behaviour: {
        idle_percentage: demo.idle_percentage,
        aggressive_events_count: 0,
        fatigue_risk_level: 'LOW',
        behaviour_score: demo.behaviour_score,
      },
      productivity: {
        completed_volume_tons: step >= 7 ? 480.0 : 320.0,
        target_volume_tons: 850.0,
        pace_percentage: step >= 7 ? 116.0 : 104.5,
        efficiency_rating: 'OPTIMAL',
      },
      prediction: {
        estimated_completion_time: '2026-09-23T14:00:00Z',
        estimated_remaining_minutes: step >= 7 ? 135 : 145,
        delay_probability_pct: step === 4 || step === 5 ? 82.0 : 12.0,
        confidence_score: 0.94,
      },
      next_best_actions: [demo.next_best_action],
    },
    immediate_safety_status: {
      operator_id: 'OP1001',
      machine_id: 'EXC-CAT-349D',
      timestamp: new Date().toISOString(),
      seatbelt_fastened: demo.seatbelt_fastened,
      seatbelt_compliance_pct: demo.seatbelt_fastened ? 99.4 : 74.2,
      proximity_warning_level: demo.active_hazard_count > 0 ? 'CRITICAL' : 'NONE',
      active_hazard_count: demo.active_hazard_count,
      overall_safety_score: demo.safety_score,
    },
    top_training_recommendation: demo.top_training_recommendation
      ? {
          recommendation_id: 'REC-FALLBACK-01',
          operator_id: 'OP1001',
          module_id: demo.top_training_recommendation.module_id,
          module_title: demo.top_training_recommendation.module_title,
          urgency: demo.top_training_recommendation.urgency as any,
          trigger_source: 'TELEMETRY_STREAM',
          reason: demo.top_training_recommendation.reason,
          recommended_at: new Date().toISOString(),
        }
      : null,
    active_alerts_count: demo.seatbelt_fastened ? (demo.active_hazard_count > 0 ? 1 : 0) : 1,
    attention_mode: demo.attention_mode,
    attention_reason: demo.attention_reason,
    demo_step: step,
    demo_step_name: demo.step_name,
  };
}

export function getFallbackTasks(): Task[] {
  return [
    {
      task_id: 'T002',
      title: 'Task T002 — Bench 2 Deep Trenching',
      description: 'Excavate and grade north sector drainage trench down to target elevation.',
      site_zone: 'Zone 4 North',
      target_volume_tons: 850,
      completed_volume_tons: 320,
      status: 'IN_PROGRESS',
      priority: 'HIGH',
      estimated_duration_minutes: 240,
      scheduled_duration_minutes: 240,
    },
    {
      task_id: 'T003',
      title: 'Task T003 — Upper Bench 3 Overburden Cut',
      description: 'Strip 180t soft overburden and stage material for subsequent haul clearance.',
      site_zone: 'Zone 4 Upper Bench',
      target_volume_tons: 400,
      completed_volume_tons: 0,
      status: 'PENDING',
      priority: 'NORMAL',
      estimated_duration_minutes: 180,
      scheduled_duration_minutes: 180,
    },
  ];
}

export function getFallbackSafetyAlerts(step: number): SafetyAlert[] {
  const alerts: SafetyAlert[] = [];
  if (step === 2) {
    alerts.push({
      alert_id: 'ALT-SEATBELT-01',
      operator_id: 'OP1001',
      timestamp: new Date().toISOString(),
      severity: 'CRITICAL',
      message: 'Operator harness unlatched while excavator hydraulics engaged.',
    });
  }
  if (step === 3) {
    alerts.push({
      alert_id: 'ALT-PROX-01',
      operator_id: 'OP1001',
      timestamp: new Date().toISOString(),
      severity: 'HIGH',
      message: 'Utility vehicle entering blind swing zone (14m range).',
    });
  }
  return alerts;
}

export function getFallbackSimilarContext(): SimilarContext {
  return {
    similar_situation_found: true,
    banner: 'SIMILAR OPERATIONAL DILEMMA DETECTED (94% MATCH)',
    historical_decision_id: 'DEC-OP1001-001',
    context_signature: 'SIG-BENCH2-WET-TRENCH',
    similarity_score_pct: 94,
    previous_context: {
      task: 'T002-BENCH2 Deep Trenching',
      machine: 'EXC-CAT-349D',
      weather: 'Rain approaching (ground saturation 28%)',
      dilemma: 'Haul fleet crusher queue coincided with incoming rain front.',
    },
    previous_action: 'Switched immediately to Upper Bench 3 pre-strip (Trajectory B: Resequence).',
    previous_prediction: 'Predicted 17 min saved, 14.8L fuel saved, 12 min early trench seal.',
    actual_result: 'Finished 15.8 min early; avoided trench flooding; 15.6L fuel saved.',
    key_learning: 'Pre-stripping soft overburden absorbs haul cycle gap without burning dead idle at 1800 RPM.',
    operator_in_control_notice: 'Past outcome provided as historical reference context only. Operator retains full operational authority.',
    recommended_training: {
      module_id: 'DECISION_AWARENESS_01',
      title: 'Decision Awareness',
      reason: 'Review past resequencing success pattern.',
    },
  };
}

export function getFallbackDecisionMemories(): DecisionMemory[] {
  return [
    {
      decision_id: 'DEC-OP1001-001',
      operator_id: 'OP1001',
      machine_id: 'EXC-CAT-349D',
      task_id: 'T002',
      timestamp: '2026-09-23T10:48:00Z',
      context_signature: 'SIG-BENCH2-WET-TRENCH',
      available_scenarios: [
        'SCEN-01-CONTINUE',
        'SCEN-02-RESEQUENCE',
        'SCEN-03-REPOSITION',
        'SCEN-04-STEEP-CUT',
      ],
      chosen_scenario: 'SCEN-02-RESEQUENCE',
      operator_reason: 'Bypassed haul truck queue before rain onset.',
      source: 'OPERATOR_DISPATCH_TWIN',
      predicted_outcome: {
        eta_minutes: 145.0,
        fuel_liters: 168.0,
        idle_minutes: 0.0,
        shift_delay_minutes: -17.0,
      },
      actual_outcome: {
        eta_minutes: 146.5,
        fuel_liters: 167.2,
        idle_minutes: 1.2,
        shift_delay_minutes: -15.8,
      },
      prediction_error: {
        eta_delta_minutes: 1.5,
        fuel_delta_liters: -0.8,
        idle_delta_minutes: 1.2,
        accuracy_pct: 98.9,
      },
    },
  ];
}
